info:
  contact: {}
paths:
  /api/member:
    post:
      description: 함수에 대한 상세 내용 쓰기
      responses:
        "201":
          description: Created
      summary: 멤버 등록
      tags:
      - 회원
swagger: "2.0"
